spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

    druid:
      filters: stat,wall,slf4j  #底层开启功能 stat：sql监控，wall防火墙
      stat-view-servlet:   #配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin

      web-stat-filter:  #监控web
        enabled: true
        url-pattern: /*

      aop-patterns: com.lingnan.admin.*  #监控SpringBean

      filter:   #详细配置
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true


mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml